### ISSUE TITLE
Test significance of tweet count (?)

### ISSUE THREAD

**Issue by kevinStekelenburg** [kevinStekelenburg/conversation-change-covid19#16]
One rq was: to what extent did the amount of tweets change? this should be tested (t-test?)

**Comment by hannesdatta** [comment]
Kevin,

Maybe this https://www.ama.org/jm-msi-special-issue-from-marketing-priorities-to-research-agendas/ helps you in formulating cool questions. Note that the RQ is not that super important. Make it “big” and “useable” for many rather than narrow and unimportant.

**Comment by kevinStekelenburg** [comment]
Thanks for thinking along! We will look into this.
