### ISSUE TITLE
Scraper dropbox credentials in external file and NOT versioning on git!

### ISSUE THREAD

**Issue by kevinStekelenburg** [kevinStekelenburg/conversation-change-covid19#17]
So Stan will not have all of his personal files accessible by the whole world 👍

**Comment by hannesdatta** [comment]
lol. good suggestion.

--> https://tilburgsciencehub.com/configure/environment-variables

**Comment by hannesdatta** [comment]
@kevinStekelenburg work with assignees. 
![image](https://user-images.githubusercontent.com/16557730/112007266-cf6c5900-8b24-11eb-9a19-e49de3fb08a0.png)

makes your workflwo smoother so you don't actually have to talk to one another all the time (although that's fun, too).

**Comment by kevinStekelenburg** [comment]
Thanks! Yes we do work with assignees, just forgot to add them right away. But thanks for the suggestion :)
