### ISSUE TITLE
Confirming that scraper WORKS on ALL DEVICES

### ISSUE THREAD

**Issue by kevinStekelenburg** [kevinStekelenburg/conversation-change-covid19#18]
Anne got an error, which was not occurring when Stan ran the scraper. SO:
- build in try and excepts (or other mechanisms) to ensure the scraper fully runs and creates output on all devices.

**Comment by hannesdatta** [comment]
rather identify the error and try to fix it. try and except just catches the error and continues. not good practice. the goal is not only to get output, but also to obtain valid output. if anne gets different stuff from stan, that's not good.
